[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
insurance_fund = "A6DYTALVAHGr3Rz7etbXFaE1XAEx56tSUQw3yueDSX4c"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kubaplata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
